### ISSUE TITLE
add sub-menus, menus tag visibility 

### ISSUE THREAD

**Issue by jeanvdr** [francescodist/matFortyTwo#19]
Hi,
It would be nice to have sub-menus on the sidenav.
Also, sometime, we need to adapt the menu with context, the possibility to change the menu-items of the sidenav menu would be great (with a visibility tag maybe ?)
Thanks
Jean Vandromme

**Comment by francescodist** [comment]
Hi Jean,
thanks for opening this issue. I have an idea on how to deal with sub-menus. Regarding the second request, could you add more detail? It could be worth to open a separate issue for the second point

**Comment by francescodist** [comment]
@jeanvdr I opened a PR ( #23 ) for this issue. Let me know what you think about it

**Comment by francescodist** [comment]
basically when you generate a nav page (-n) you can add a -g (--group) parameter to set a group for that page. The pages will be grouped in the sidenav using this value (which will also be the title shown for the group). Since this is also going to be the title, values with spaces are allowed, but you will need to use quotes. 
E.G.
`npm run genpage -- -n child-one -g 'group one'`

**Comment by jeanvdr** [comment]
this is very, very nicely and effectively done !
a -t option for page's title (different from page's name) in genpage script would also be nice
Thanks +++
